version: '3'
services:
    nginx:
        build: ./nginx/
        container_name: nginx-container
        ports:
            - 80:80
        links:
            - php
        volumes:
            - ../:/var/www/html

    php:
        build: ./php/
        container_name: php-container
        expose:
            - 9000
        links:
            - mysql
        volumes:
            - ../:/var/www/html

    mysql:
        image: mysql:8.0
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo
            MYSQL_PASSWORD: root
        ports:
            - '4306:3306'
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 9001
        depends_on:
            - mysql
